kind: Pod
apiVersion: v1
metadata:
  name: hostpath-test-pod
spec:
  containers:
  - name: hostpath-test-container
    image: gcr.io/google_containers/busybox:1.24
    command: ["/bin/sh", "-c", "while true; do date >> /mnt/dates; sleep 10; done"]
    volumeMounts:
      - name: hostpath-volume
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: hostpath-volume
      persistentVolumeClaim:
        claimName: hostpath-test-claim
